### ISSUE TITLE
Code editor not displayed in Mac OS 10.14.6

### ISSUE THREAD

**Issue by BoDonkey** [ehigiepaul/PGDevTool#1]
Library package loads into Pinegrow running on 10.14.6 without error, but only an empty, docked window appears upon opening code editor.

## Steps to reproduce
1) Open Pinegrow and load 'PGDevTools.js' in the Libraries and Plugins Manager.
2) Open a new or existing page/project
3) Press the `F7` key

This results in an empty, docked window with a dropdown for language selection.
![image](https://user-images.githubusercontent.com/13168224/107877262-4dd83a00-6e99-11eb-89bf-23d21857213a.png)
If the DevTools are open there is a 404 get error
![image](https://user-images.githubusercontent.com/13168224/107877284-68121800-6e99-11eb-9506-674c98ef053c.png)
![image](https://user-images.githubusercontent.com/13168224/107877287-6f392600-6e99-11eb-90b2-29956a23779f.png)

**Comment by BoDonkey** [comment]
Note - same error with new Mac release - error location is always the file being opened, always line 57.

**Comment by tenluap** [comment]
Noted, it looks like a path issue, will go deep into it.

**Comment by schpengle** [comment]
Confirming the above and also adding.

1. Adding that Custom Pinegrow workspace layout breaks the appearing of the Plugins Monaco editor, it does not even appear when pressing F7, and so cant be confirmed as empty - although previously this behaviour was noted.

2. Loading and Activating the Monaco editor plugin, with a custom Workspace layout (here, dual monitors, custom 
workspace) actually BREAKS the default  Pinegrow Editors ability to open and view the CSS stylesheets through the usual method. Instead, the Freshly opened CSS Stylesheet tabs, that usually open NEXT to the open Page, code view appear bizarrely above the tree panel view - and cannot be selected.

3. If these misplaced CSS Stylesheet tabs are dragged first to the boundary between 2 panels, then to where they should actually be (I think - this is the place where the Monaco editor appears -when it appears) they are once more empty - like the Monaco editor would be, in this current Beta state, if it was to be present. It is as though after loading the plugin, it *takes* that space, fails to render content, and then prevents the default app from actually rendering its own content in that place too - to the point that even the new tabs cant be created in that same place.

4. only completely unloading the plugin helps to resolve this. deactivating does not help and, after unloading and reloading when having only deactivated, but NOT unloaded, Pinegrow will load, but complain in 3 stages about broken workspace layouts and force the User to restart the App.

following are some diagrams to hopefully explain and even more hopefully, in the right order! :-)

The Following is actually the right monitor, mislabelled by my good self!

![image](https://user-images.githubusercontent.com/3315030/108114408-a7ef2000-7090-11eb-8749-a8cd27ebbb9c.png)

in this, an element has been selected in layout pane (on the other,left hand monitor, as seen in next picture that follows) and in the CSS style editor pane (This, right hand monitor - mislabelled as left)  I am attempting to open the Stylesheet in the PG native Editors Code view pane.
I see nothing happening where I expect, the tab to appear (over on the left monitor -code view, editor pane), but see some movement somewhere, so expand and move panels, then notice the misplaced Stylesheet code view tabs have appeared above the tree view pane! partially obscuring the Tree panes search function box.

as is seen here.
![image](https://user-images.githubusercontent.com/3315030/108114862-3e234600-7091-11eb-894b-6f067cf2cbcb.png)

And AFTER dragging these stylesheet tabs from the top of the Tree view, This **startstyles.css** artefact was left on the screen unable to move it, the editor has been closed.

![image](https://user-images.githubusercontent.com/3315030/108115871-a4f52f00-7092-11eb-960a-434c390b87a1.png)

I now have to restart PG, as the NATIVE Pinegrow CSS STYLESHEET view no longer works at all.
I had to unload the plugin as Deactiving plugin alone did not work.

And then, when trying to reload Pinegrow, while STILL having the plugin LOADED (but deactivated) the following sequence of events is noted, before having to unload the plugin altogether and then restarting it.

![Screenshot 2021-02-16 at 19 01 23](https://user-images.githubusercontent.com/3315030/108116194-1d5bf000-7093-11eb-808d-2720e7f3a482.png)

![Screenshot 2021-02-16 at 19 04 20](https://user-images.githubusercontent.com/3315030/108116272-36fd3780-7093-11eb-872a-e23592948ff9.png)

![Screenshot 2021-02-16 at 19 05 11](https://user-images.githubusercontent.com/3315030/108116288-3fee0900-7093-11eb-95ed-5856e9e1b2b6.png)

**Comment by schpengle** [comment]
**UPDATE**

While testing the Monaco Editor plugin, I actually discovered a bug in Pinegrow itself, with **Undocked Panels** /custom workspace that broke the Pinegrow's Visual Editors ability to render overwritten /duplicated CSS styles correctly.

So Custom Layout implementation, effects Visual Editor's ability to render code state logic (greyed out/struck through if overwritten.) correctly.
Also, it broke the relationship between The content of the Visual tool , and the Native Text editor itself.

Ie, differing numbers of the same duplicated  (body) style rulesets were appearing in both the visual editor and Text editor displays. (3 rulesets in one, 4 in the other)

Referenced here

https://forum.pinegrow.com/t/duplicate-style-ruleset-not-working-correctly-update-not-solved-it-reverted-then-sorted-iteself/4980/23?u=schpengle

This is now a recognised bug, and is being worked on by the Pinegrow team, but this, or its future fix, may hinder the correct function of this Monaco Editor Plugin, so I am writing here, to update this informatioin, incase this Monaco Editor Plugin is being debugged, in order to work around an actual Pinegrow bug.. which may soon be fixed, rendering the Monaco plugins work on a fix, redundant, or the Pinegrow fix may itself, break this plugin again.

This is updated/mentioned since, the custom workspace layout of Pinegrow seemed to interfere with this Monaco Plugin's functionality, yet, the Pinegrow custom workspace layout is itself, actually now shown to have a bug, which can effect the contents of the native text/visual editors.

Maybe wait until/track the Pinegrow fix for the above, or check in with PineGrow devs about the fix and if it will affect your plugins implementation/ability to function first.

**Comment by tenluap** [comment]
Thanks @schpengle, I started a feature request that turned up to be a project now, I will take an in depth view on this issue. Changing workspace that brakes the devtool will be part of my next  bug fix.

Please kindly download the latest release and there's an installation video to guide users.

**Comment by schpengle** [comment]
Well!
Well done! Monaco editor works on Mac os x 10.14.6, Mojave, and is populated with the correct file content, 
with standard 3 Column display.
That is 1.0.8 Beta

The Terminal also spawns, but doesn't appear to be active, I can see no cursor in it.

Also, on the great new *Devtools* Menu item, I see the shortcuts for both Terminal and Editor, but they are transposed and should be the other way around.

![Screenshot 2021-03-01 at 23 54 37](https://user-images.githubusercontent.com/3315030/109575930-b30f6a80-7aea-11eb-8960-36aa12084569.png)

Each listed command works as it shoudl but the listed shortcuts are the wrong way around.

I wil test the other layouts shortly etc and see If i Can get the terminal to work/am doing something wrong my end.
but well done :)

**Comment by tenluap** [comment]
Closed ehigiepaul/pgmonaco@5a2799f

**Comment by tenluap** [comment]
@schpengle the shortcut label has been fixed and will be available in the next release. Thanks for testing, As for you terminal try rebuilding, if that fail will look into it.

**Comment by schpengle** [comment]
Well, Monaco editor is still broken in Custom Workspace layout (appears in a none standard place, next to the tree)
and is empty, has no code content, also, the following error is generated and appears briefly on the Pinegrow app before disappearing. 

Type error cannot read property of undefined.

-But this could be the PG custom workspace layout bug.
I dont know if this error is PG or Plugin generated.

Also, I have tried the rebuild tool for the terminal, that has made no difference, it still doesnt function correctly, -ie, 
it DOES now appear, but alongside the empty monaco tab, next to tree view.
BUT......

I have just been playing with node and NVM, and appear to have a problem with my .bash_profile environment variables, so I will have to check that out.
VSCode has just started complaining about being unable to find npm, pnpm at the same time.

Also, If I revert to standard 3 column workspace layout, without restarting PG, then the monaco editor appears in the correct place fully populated with code once more.
Great.

So swapping back and fore to Custom workspace and back to standard, 3 column layout breaks, then fixes Monaco functionaliy respectively.

I will check more this evening, after fixing my environment variables.
keep it up :)
